/********************************************************************************
Student Name and Surname: Sercan Þahan
Student Number: 150140005
Lecture Name: BIL105E - Introduction to Scientific and Engineering Computing (C)
Homework 2
********************************************************************************/
#include <stdio.h>
#include <stdlib.h>

void midprng(long long seed, long long numsample);
void lsdprng(long long seed, long long numsample);
void printhistogram(int percentage);

int main()
{
	int function;
	long long seed, numsample;
	
	printf("Choose PRNG function:\n1- MID-PRNG\n2- LSD-PRNG\n");
	scanf("%d", &function);
	
	while(function != 1 && function != 2)//Prevents user from entering a number different than 1 or 2
	{
		printf("You choosed an invalid function. Please enter a valid function number.\n\nChoose PRNG function:\n1- MID-PRNG\n2- LSD-PRNG\n");
		scanf("%d", &function);
	}
	printf("\nEnter the 5 digit seed number:\n");//Asks user to enter a five-digit number
	scanf("%lld", &seed);
	if (function == 1)//Starts MID-PRNG
	{
		while(seed > 99999 || seed < 10000)//Forces user to enter a five-digit number
		{
			printf("\nPlease enter a 5 digit number:\n");
			scanf("%lld", &seed);
		}
		printf("\nEnter the number of samples:\n");
		scanf("%lld", &numsample);//Asks user to enter number of samples
		printf("\n%lld random numbers were generated by using MID-PRNG\n", numsample);
		
		midprng(seed, numsample);
	}
	else if (function == 2)//Starts LSD-PRNG
	{
		while(seed > 99999 || seed < 10000)//Forces user to enter a five-digit number
		{
			printf("\nPlease enter a 5 digit number:\n");
			scanf("%lld", &seed);
		}
		while(seed % 5 == 0 || seed % 2 == 0)//Prevents user from entering a number that is even or ends with 5
		{
			printf("\nPlease enter another 5 digit number:\n");
			scanf("%lld", &seed);
		}
		printf("\nEnter the number of samples:\n");
		scanf("%lld", &numsample);//Asks user to enter number of samples
		printf("\n%lld random numbers were generated by using LSD-PRNG\n", numsample);
		
		lsdprng(seed, numsample);
	}
	return 0;
}

void midprng(long long seed, long long numsample)
{
	long long square;
	long long newnumber1, newnumber2, range;
	int range1 = 0, range2 = 0, range3 = 0, range4 = 0, range5 = 0;
	int percentage1, percentage2, percentage3, percentage4, percentage5;
	int total_range;
	
	while(numsample > 0)
	{
		square = seed * seed;//Finding square of seed and removing digits to take middle five digits as new seed value as stated in pdf
		if(square >= 1000000000)
		{
			newnumber1 = square % 100000000;
			newnumber2 = newnumber1 / 1000;
			seed = newnumber2;
		}
		else if(square < 1000000000 && square >= 100000000)
		{
			newnumber1 = square % 10000000;
			newnumber2 = newnumber1 / 100;
			seed = newnumber2;
		}
		else if(square < 100000000 && square >= 10000000)
		{
			newnumber1 = square % 10000000;
			newnumber2 = newnumber1 / 100;
			seed = newnumber2;
		}
		else if(square < 10000000 && square >= 1000000)
		{
			newnumber1 = square % 1000000;
			newnumber2 = newnumber1 / 10;
			seed = newnumber2;
		}
		else if(square < 1000000 && square >= 100000)
		{
			newnumber1 = square;
			newnumber2 = newnumber1 / 10;
			seed = newnumber2;
		}
		else if(square < 100000)
		{
			newnumber1 = square;
			newnumber2 = newnumber1;
			seed = newnumber2;
		}
		range = newnumber2 % 500 + 1;//Finding range of number with base 500 
		//Incrementing numbers of ranges depending on range of number
		if(range <= 100)
		{
			range1++;
		}
		else if(range <= 200)
		{
			range2++;
		}
		else if(range <= 300)
		{
			range3++;
		}
		else if(range <= 400)
		{
			range4++;
		}
		else if(range <= 500)
		{
			range5++;
		}
		numsample--;//Decrementing numsample to prevent a infinite while loop
	}
	//Printing range percentages and histograms
	printf("Range:\n");
	total_range = range1 + range2 + range3 + range4 + range5;
	
	percentage1 = range1*100 / total_range;
	printf("1-100  : %%%d ", percentage1);
	printhistogram(percentage1);
	
	percentage2 = range2*100 / total_range;
	printf("101-200: %%%d ", percentage2);
	printhistogram(percentage2);
	
	percentage3 = range3*100 / total_range;
	printf("201-300: %%%d ", percentage3);
	printhistogram(percentage3);
	
	percentage4 = range4*100 / total_range;
	printf("301-400: %%%d ", percentage4);
	printhistogram(percentage4);
	
	percentage5 = range5*100 / total_range;
	printf("401-500: %%%d ", percentage5);
	printhistogram(percentage5);
}

void lsdprng(long long seed, long long numsample)
{
	long long product, number;
	int range, total_range, range1=0, range2=0, range3=0, range4=0, range5=0;
	int percentage1, percentage2, percentage3, percentage4, percentage5;
	
	while(numsample > 0)
	{
		product = seed * 73;
		number = product % 100000;//Removing digits to find new seed value
		range = number % 500 + 1;//Finding range of number with base 500 
		//Incrementing numbers of ranges depending on range of number
		if(range <= 100)
		{
			range1++;
		}
		else if(range <= 200)
		{
			range2++;
		}
		else if(range <= 300)
		{
			range3++;
		}
		else if(range <= 400)
		{
			range4++;
		}
		else if(range <= 500)
		{
			range5++;
		}
		seed = number;//Assigning new value to seed variable
		numsample--;//Decrementing numsample to prevent an infinite while loop
	}
	//Printing range percentages and histograms
	printf("Range:\n");
	total_range = range1 + range2 + range3 + range4 + range5;
	
	percentage1 = range1*100 / total_range;
	printf("1-100: %%%d", percentage1);
	printhistogram(percentage1);
	
	percentage2 = range2*100 / total_range;
	printf("101-200: %%%d", percentage2);
	printhistogram(percentage2);
	
	percentage3 = range3*100 / total_range;
	printf("201-300: %%%d", percentage3);
	printhistogram(percentage3);
	
	percentage4 = range4*100 / total_range;
	printf("301-400: %%%d", percentage4);
	printhistogram(percentage4);
	
	percentage5 = range5*100 / total_range;
	printf("401-500: %%%d", percentage5);
	printhistogram(percentage5);
}

void printhistogram(int percentage)//Function to print histograms
{
	while(percentage > 0)
	{
		printf("*");
		percentage--;
	}
	printf("\n");
}
